# Generated by Django 5.0.2 on 2024-02-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_rename_endpoints_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='type',
            field=models.CharField(default='NULL', max_length=140),
        ),
    ]
