# Generated by Django 5.0.2 on 2024-02-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='humidity',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='moisture',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='ph',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='temparature',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
