# Generated by Django 5.0.2 on 2024-02-26 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0005_alter_data_humidity_alter_data_moisture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('name', models.CharField(max_length=140)),
                ('location', models.CharField(default='NULL', max_length=140)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='uuid',
        ),
        migrations.AddField(
            model_name='data',
            name='endpoint',
            field=models.ForeignKey(blank=True, db_column='endpoint', null=True, on_delete=django.db.models.deletion.CASCADE, to='garden.endpoint', to_field='uuid'),
        ),
        migrations.AddField(
            model_name='data',
            name='plant',
            field=models.ForeignKey(blank=True, db_column='plant', null=True, on_delete=django.db.models.deletion.CASCADE, to='garden.plant', to_field='uuid'),
        ),
    ]
