# Generated by Django 5.0.2 on 2024-04-21 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0007_data_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='PlantAutoData',
        ),
        migrations.CreateModel(
            name='PlantUsrData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer', models.CharField(max_length=140)),
                ('notes', models.TextField()),
                ('plant', models.ForeignKey(db_column='plant', on_delete=django.db.models.deletion.CASCADE, to='garden.plant', to_field='uuid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
