# Generated by Django 5.0.2 on 2024-04-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0008_rename_data_plantautodata_plantusrdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantusrdata',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
