# Generated by Django 5.0.2 on 2024-04-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0009_plantusrdata_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantusrdata',
            name='fertilizer',
            field=models.CharField(blank=True, default=None, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='plantusrdata',
            name='notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
