# Generated by Django 5.0.2 on 2024-04-25 04:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0012_alter_plantusrdata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantusrdata',
            name='time',
        ),
        migrations.AddField(
            model_name='plantusrdata',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
