# Generated by Django 5.0.2 on 2024-04-21 02:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aqua', '0002_usrdata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsrData',
            new_name='TankUsrData',
        ),
    ]
